version: "3.3"
services:
  # Metrics store
  influxdb:
    image: influxdb:latest
    container_name: cb-restapigw-influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - './conf/env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  # Metrics UI
  grafana:
    image: grafana/grafana
    container_name: cb-restapigw-grafana
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - './conf/env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    user: "0"

  # Trace store and UI
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cb-restapigw-jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  # Fake API
#  fake_api:
#    image: jaxgeller/lwan
#    container_name: fake_api
#    volumes:
#      - ./data/lwan:/lwan/wwwroot
#    ports:
#      - "8100:8080"

  # HMAC Server
#  hmac_site:
#    build:
#      context: ./web
#    container_name: hmac_server
#    volumes:
#      - ./web/public:/app/public
#      - ./web/conf:/app/conf
#    ports:
#      - "8010:8010"

# The priority used by Compose to choose which env var value to use:
# 1. Compose file
# 2. Shell environment variables
# 3. Environment file
# 4. Dockerfile
# 5. Variable is not defined

  # CB-Spider
  cb-spider:
    image: cloudbaristaorg/cb-spider:v0.2.0-20201025
    container_name: cb-spider
    ports:
      - "1024:1024"
      - "2048:2048"
    volumes:
      - ./conf/cb-spider:/root/go/src/github.com/cloud-barista/cb-spider/conf
      - ./data/cb-spider/meta_db:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/dat
      - ./data/cb-spider/log:/root/go/src/github.com/cloud-barista/cb-spider/log
    depends_on:
      - cb-restapigw


  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:v0.2.0-20201023
    container_name: cb-tumblebug
    ports:
      - "1323:1323"
      - "50252:50252"
    depends_on:
      - cb-restapigw
      - cb-spider
#     - cb-tumblebug-mysql
    volumes:
      - ./conf/cb-tumblebug:/app/conf
      - ./data/cb-tumblebug/meta_db:/app/meta_db/dat
      - ./data/cb-tumblebug/log:/app/log
    environment:
      - SPIDER_CALL_METHOD=GRPC
      - SPIDER_REST_URL=http://cb-restapigw:8000/spider
      - DRAGONFLY_REST_URL=http://cb-restapigw:8000/dragonfly
      - API_USERNAME=default
      - API_PASSWORD=default
#     - DB_URL=cb-tumblebug-mysql:3306
#     - DB_DATABASE=cb_tumblebug
#     - DB_USER=cb_tumblebug
#     - DB_PASSWORD=cb_tumblebug
#     - GODEBUG=netdns=go

# cb-tumblebug-mysql:
#   image: mysql
#   container_name: cb-tumblebug-mysql
#   ports:
#     - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#   environment: # -e 옵션
#     MYSQL_ROOT_PASSWORD: "cloud-barista"  # MYSQL 패스워드 설정 옵션
#     MYSQL_DATABASE: cb_tumblebug
#     MYSQL_USER: cb_tumblebug
#     MYSQL_PASSWORD: cb_tumblebug
#   command: # 명령어 실행
#     - --character-set-server=utf8mb4
#     - --collation-server=utf8mb4_unicode_ci
#     - --default-authentication-plugin=mysql_native_password
#   volumes:
#     - ./data/cb-tumblebug-mysql:/var/lib/mysql

# cb-phpmyadmin:
#   image: phpmyadmin/phpmyadmin
#   container_name: cb-phpmyadmin
#   ports:
#     - 80:80
#   environment: # -e 옵션
#     PMA_HOSTS: cb-tumblebug-mysql
#     PMA_PORTS: 3306
#     PMA_USER: cb_tumblebug
#     PMA_PASSWORD: cb_tumblebug
#   links:
#     - cb-tumblebug-mysql
#   depends_on:
#     - cb-tumblebug-mysql

  cb-tumblebug-phpliteadmin:
    image: acttaiwan/phpliteadmin
#   image: jihoons/phpliteadmin
    container_name: cb-tumblebug-phpliteadmin
    ports:
      - 2015:2015
    volumes:
      - ./data/cb-tumblebug/meta_db:/db

  # CB-Ladybug
  cb-ladybug:
    image: cloudbaristaorg/cb-ladybug:v0.2.0-20201021
    container_name: cb-ladybug
    ports:
      - "8080:8080"
    depends_on:
      - cb-restapigw
      - cb-spider
      - cb-tumblebug
    volumes:
      - ./conf/cb-ladybug:/app/conf
      - ./data/cb-ladybug/meta_db:/app/meta_db/dat
      - ./data/cb-ladybug/log:/app/log
    environment:
#     - CBLOG_ROOT=/app
#     - CBSTORE_ROOT=/app
#     - APP_ROOT=/app
      - SPIDER_URL=http://cb-restapigw:8000/spider
      - TUMBLEBUG_URL=http://cb-restapigw:8000/tumblebug
      - BASE_PATH=/ladybug
      - API_USERNAME=default
      - API_PASSWORD=default

  # CB-Dragonfly
  cb-dragonfly:
    image: cloudbaristaorg/cb-dragonfly:espresso-v0.1-inno-test
    container_name: cb-dragonfly
    volumes:
      - ./conf/cb-dragonfly:/go/src/github.com/cloud-barista/cb-dragonfly/conf
      - ./data/cb-dragonfly/log:/go/src/github.com/cloud-barista/cb-dragonfly/log
    ports:
      - 8094:8094/udp
      - 9090:9090
    depends_on:
#     - cb-restapigw
      - cb-dragonfly-etcd
      - cb-dragonfly-influxdb
      - cb-dragonfly-kapacitor
    environment:
      - CBSTORE_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBLOG_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBMON_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
#     - DRAGONFLY_INFLUXDB_URL=cb-dragonfly-influxdb:8086
    restart: always
    security_opt:
      - no-new-privileges

  # InfluxDB for Dragonfly
  cb-dragonfly-influxdb:
    image: influxdb:1.8-alpine
    container_name: cb-dragonfly-influxdb
    ports:
      - 28086:8086
    environment:
      - PRE_CREATE_DB=cbmon
      - INFLUXDB_DB=cbmon
      - INFLUXDB_ADMIN_USER=cbmon
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: always

  # etcd for Dragonfly
  cb-dragonfly-etcd:
    image: bitnami/etcd:3.3.11
    container_name: cb-dragonfly-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://cb-dragonfly-etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    restart: always

  # Kapacitor for CB-Dragonfly
  cb-dragonfly-kapacitor:
    image: kapacitor:1.5
    container_name: cb-dragonfly-kapacitor
    ports:
      - 9092:9092
    environment:
      - KAPACITOR_HOSTNAME=cb-dragonfly-kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://cb-dragonfly-influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=cbmon
      - KAPACITOR_INFLUXDB_0_PASSWORD=password
    depends_on:
      - cb-dragonfly-influxdb
    restart: always

  # CB-Webtool
  cb-webtool:
    image: cloudbaristaorg/cb-webtool:v0.2.0-20201020
    container_name: cb-webtool
    ports:
      - "1234:1234"
    depends_on:
      - cb-restapigw
      - cb-spider
      - cb-tumblebug
    environment:
     #- SPIDER_URL=http://cb-restapigw:8000/spider
     #- TUMBLE_URL=http://cb-restapigw:8000/tumblebug
      - API_GW=http://cb-restapigw:8000
      - SPIDER_URL=http://cb-restapigw:8000/spider
      - TUMBLE_URL=http://cb-restapigw:8000/tumblebug
      - DRAGONFLY_URL=http://cb-restapigw:8000/dragonfly
      - LADYBUG_URL=http://cb-restapigw:8000/ladybug
      - LoginEmail=admin
      - LoginPassword=admin

  # CB-RESTAPIGW SERVICE
  cb-restapigw:
    image: cloudbaristaorg/cb-restapigw:v0.2.0-20201022
    container_name: cb-restapigw
    volumes:
      - ./conf/cb-restapigw:/app/conf
#     - ./data/cb-restapigw/log:/app/log
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - influxdb
      - grafana
      - jaeger
#     - hmac_site
#     - fake_api
#     - cb-spider
#     - cb-tumblebug

        #networks:
        #  default:
        #    external:
        #      name: cboperator_default


