definitions:
  # Health
  - name: 'Ladybug GET /healthy'
    active: true
    endpoint: /ladybug/healthy
    method: GET
    backend:
      - hosts:
        - host: http://cb-ladybug:1470
          weight: 0
        url_pattern: /ladybug/healthy
        middleware:
          mw-http:
            return_error_details: GET_healthy

  # Get Ladybug cluster
  - name: 'Ladybug GET /clusters'
    active: true
    endpoint: /ladybug/ns/:nsId/clusters
    method: GET
    backend:
      - hosts:
        - host: http://cb-ladybug:1470
          weight: 0
        url_pattern: /ladybug/ns/{{.NsId}}/clusters
        middleware:
          mw-http:
            return_error_details: GET_clusters

  - name: 'Ladybug GET /clusters/:clusterId'
    active: true
    endpoint: /ladybug/ns/:nsId/clusters/:clusterId
    method: GET
    backend:
      - hosts:
        - host: http://cb-ladybug:1470
          weight: 0
        url_pattern: /ladybug/ns/{{.NsId}}/clusters/{{.ClusterId}}
        middleware:
          mw-http:
            return_error_details: GET_cluster

  # Get Ladybug cluster node
  - name: 'Ladybug GET /clusters/:clusterId/nodes'
    active: true
    endpoint: /ladybug/ns/:nsId/clusters/:clusterId/nodes
    method: GET
    backend:
      - hosts:
        - host: http://cb-ladybug:1470
          weight: 0
        url_pattern: /ladybug/ns/{{.NsId}}/clusters/{{.ClusterId}}/nodes
        middleware:
          mw-http:
            return_error_details: GET_nodes

  - name: 'Ladybug GET /clusters/:clusterId/nodes/:nodeId'
    active: true
    endpoint: /ladybug/ns/:nsId/clusters/:clusterId/nodes/:nodeId
    method: GET
    backend:
      - hosts:
        - host: http://cb-ladybug:1470
          weight: 0
        url_pattern: /ladybug/ns/{{.NsId}}/clusters/{{.ClusterId}}/nodes/{{.NodeId}}
        middleware:
          mw-http:
            return_error_details: GET_node
